M48
; DRILL file {KiCad 9.0.3} date 2026-07-21T15:40:27+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-21T15:40:27+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.750
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.300
%
G90
G05
T1
X146.29Y-104.755
X146.29Y-106.025
X146.29Y-107.295
T2
X135.0Y-106.525
X138.4Y-106.525
T3
X138.215Y-88.453
X143.295Y-88.453
M30
